# Generated by Django 5.0.1 on 2024-02-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_form', '0002_remove_formdata_example_form_control_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='project_detail',
            new_name='projectdetail',
        ),
    ]
